### PR TITLE
Update StringIO to 3.0.8

### PR DESCRIPTION
**Pull request by bluefroguk1**
StringIO updated to 3.0.8 (to support Ruby 3.3)

### CODE REVIEW

**Comment by bluefroguk1** [comment]
Updating to 3.0.9+ breaks 'Add Date/Time' button

**Comment by mentalstring** [comment]
Which/where is the button that breaks? With 3.1.0 I didn't spot it during my tests when doing basic add/editing of an event.

That said, when updating StringIO (to any 3.0.7+ version), I noticed that this starts happening in the list of topics with an event:
746066f1060ea6519ff4981d76fdbeb834f1f405_2_690x306

Do you have the same issue?

**Comment by timmsantos** [comment]
@mentalstring , I'm experiencing the same thing as well, we did v3.0.7 and it changed all our date times in the topic list to [object Object]

**Comment by bluefroguk1** [comment]
> Which/where is the button that breaks? With 3.1.0 I didn't spot it during my tests when doing basic add/editing of an event.

image

The button seems to vanish in later versions. Not sure why (sadly don't know my way around Ember enough to investigate properly)

**Comment by bluefroguk1** [comment]
I can confirm we are getting the same [object Object] issue

I might be using the plug in differently to you both - we hide the topic that the events are made on, as our users only interact with them via the the calendar which is working correctly. Which explains why i didn't notice the bug,

**Comment by angusmcleod** [comment]
Fixed in https://github.com/paviliondev/discourse-events/pull/136

**Pull request closed without merging**
