### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**
- Update german
- Remove unused strings

### CODE REVIEW

**Comment by angusmcleod** [comment]
@Justman10000 Thanks again. With this one too, there's no need to remove locale strings, even if they're not currently used. Once that's updated, happy to merge this 👍

**Comment by Justman10000** [comment]
@angusmcleod

Better?

**Comment by Justman10000** [comment]
@angusmcleod

**Comment by angusmcleod** [comment]
@Justman10000 Thanks.

**Pull request merged**
