### PR TITLE
rake task to migrate to official discourse-calendar events

### PR DESCRIPTION
**Pull request by fzngagan**

### CODE REVIEW

**Comment by nathan-nz** [comment]
This could be very handy - any chance it could be pushed through?

**Comment by jeffbyrnes** [comment]
+1 that this would be quite handy!

**Comment by jeffbyrnes** [comment]
@angusmcleod what led to the decision to close this without merging? Will this be provided via some other means, or not at all?

**Comment by angusmcleod** [comment]
@jeffbyrnes A few reasons Jeff, mostly technical. If you want to use this rake task you can check out this branch on your instance. Just put the branch in the git clone of the plugin in your app.yml file.

```
git clone -b migration https://github.com/paviliondev/discourse-events.git
```

**Comment by jeffbyrnes** [comment]
@angusmcleod no problem, just curious! Thanks for the help to use it despite not merging 🙇🏻

**Pull request closed without merging**
