### PR TITLE
ICS export is broken; UID's constantly change. (And add Sequence)

### PR DESCRIPTION
**Pull request by md-misko**
https://github.com/paviliondev/discourse-events/issues/51#

### CODE REVIEW

**Comment by angusmcleod** [comment]
@md-misko Amazing! Thanks for taking the time to work on this.

@fzngagan Same as before, you take a first go at reviewing this. Then I'll also do a review.

**Comment by fzngagan** [comment]
I'll take a look this weekend.

**Comment by fzngagan** [comment]
Me and @angusmcleod checked this out. It seems to fix the issue but the `uid` should match a certain format according to the icalendar specs. We thought that if we're changing it, lets make it match the spec accurately.

**Comment by md-misko** [comment]
@fzngagan, @angusmcleod, does this mean you are planning a fix yourself, and if so, when?

The current issue with the changing UIDs at every sync is causing serious duplication issues on my instance: I have an external process (which depends on event UIDs) which now fires (per each "unique" event) on every sync---because there are "new" events after every sync---instead just once.

**Comment by fzngagan** [comment]
@md-misko . I'll get this fixed within this week.

**Comment by fzngagan** [comment]
@md-misko 
Here is the dev branch of the feature.
https://github.com/fzngagan/discourse-events/tree/add-uid-to-events

Please do try it out and tell us whether it solves the issue.

**Pull request closed without merging**
