### PR TITLE
Update stringio again...

### PR DESCRIPTION
**Pull request by o7n**
Ok so 5 minutes after my previous PR another update to stringio was released to core tests-passed 😱

### CODE REVIEW

**Comment by angusmcleod** [comment]
I wonder why we're specifying this independently...

**Comment by angusmcleod** [comment]
More of a question to myself than you.

**Comment by o7n** [comment]
> More of a question to myself than you.

But I do have the answer, actually it was in the previous PR because I asked myself the same this morning

> Stringio is now part of Rails 7.1 but on stable it's still necessary to explicitly include the stringio gem so it cannot be removed yet until we arrive at 3.3 stable

**Comment by angusmcleod** [comment]
Oh! Do we need to do anything more here then?

**Comment by o7n** [comment]
I _think_ you need to revert your commit `dd64214` since stable won't have the stringio gem now and that would be a problem.

I'm not sure what code depends on it so it's hard to test and know for sure.

**Comment by angusmcleod** [comment]
Yeah, you're right. I've reverted that commit and merging this.

**Pull request merged**
