### PR TITLE
added a feature to serialize post custom fields to draft

### PR DESCRIPTION
**Pull request by fzngagan**

### CODE REVIEW

**Comment by fzngagan** [comment]
I've assigned a do not merge label because the plugin-api version isn't bumped yet. Once its bumped, I'll use that and add another commit.

**Comment by angusmcleod** [comment]
@fzngagan Is this ready to be merged?

**Comment by fzngagan** [comment]
Yes man

**Comment by angusmcleod** [comment]
@fzngagan Is there a reason we need to have this in a seperate ``withPluginApi`` block? Can't we just increase the api version number of the existing block? Are the existing methods used in that block deprecated in the latest api version?

**Comment by fzngagan** [comment]
@angusmcleod, The reason for calling `serializeToDraft` in separate block is that it's only available in `0.8.33` version of plugin-api. If I put it in an existing block, I could very well get a js error if that site's Discourse would be at a version less than `0.8.33`. 

If I change the existing block's version, the whole of it won't be executed if the version of site's plugin-api is below `0.8.33`.

The only thing plugin-api checks is, whether the `requested` plugin-api version is less or equal to the current plugin-api version.

**Comment by angusmcleod** [comment]
@fzngagan Got it. Thanks!

**Comment by fzngagan** [comment]
That was quick. Thanks

**Pull request merged**
